# ---DVA2C specific parameters ---
# DVA2C is equivalent to NTWA2C
hidden_dim: 128 # MPE
lr: 0.0005 # MPE
standardise_rewards: False # MPE
entropy_coef: 0.01  # MPE
q_nstep: 10 # MPE: 1 corresponds to normal r + gammaV
# update the target network every {} training steps
target_update_interval_or_tau: 0.01 # MPE
use_rnn: False # MPE

action_selector: "soft_policies"
mask_before_softmax: True

runner: "parallel"
buffer_size: 10
batch_size_run: 10
batch_size: 10

env_args:
  state_last_action: False # critic adds last action internally
  joint_rewards: False
  time_limit: 25 # MPE

obs_last_action: False
obs_agent_id: False
obs_individual_obs: False

mac: "dac"
agent: "rnn_ns"
agent_output_type: "pi_logits"
learner: "actor_critic_distributed_v_learner"
standardise_returns: False
critic_type: "ac_critic_networked" # All weights begin at the same place.

# Networked agents
networked_edges: 1  # maps n_agents: n_edges
networked_rounds: 5   # At each consensus round try this many consensus matrices.
networked_interval: 10 # Try consensus at every networked_interval number of training steps.
networked_policy: False # Try consensus on the actor
# networked_joint_actions: True # Agents observe the full action space (and joint_rewards: False)

name: "dva2c"
t_max: 20_050_000
