# --- IA2C NS specific parameters ---
hidden_dim: 64 # RWARE
lr: 0.0005 # RWARE

action_selector: "soft_policies"
mask_before_softmax: True

runner: "parallel"

buffer_size: 10
batch_size_run: 10
batch_size: 10

env_args:
  state_last_action: False # critic adds last action internally
  joint_rewards: True
  shared_rewards: False
  time_limit: 500 # RWARE

# update the target network every {} training steps
target_update_interval_or_tau: 0.01  # RWARE


obs_agent_id: False
obs_last_action: False
obs_individual_obs: False

mac: "non_shared_mac"
agent: "rnn_ns"
agent_output_type: "pi_logits"
learner: "actor_critic_learner"
entropy_coef: 0.01
standardise_returns: False
standardise_rewards: True
use_rnn: False  # RWARE
q_nstep: 5  # RWARE 1 corresponds to normal r + gammaV
critic_type: "ac_critic_ns"
name: "ia2c_ns"

t_max: 20_050_000
