# --- IA2C specific parameters ---
hidden_dim: 64    # RWARE
lr: 0.0005        # RWARE
standardise_rewards: True  # RWARE
use_rnn: True   # RWARE
entropy_coef: 0.01  # RWARE
# update the target network every {} training steps
target_update_interval_or_tau: 0.01   # RWARE
q_nstep: 5 # 1 corresponds to normal r + gammaV 

action_selector: "soft_policies"
mask_before_softmax: True

runner: "parallel"

buffer_size: 10
batch_size_run: 10
batch_size: 10

env_args:
  state_last_action: False # critic adds last action internally
  joint_reward: True
  shared_reward: False


obs_agent_id: True
obs_last_action: False
obs_individual_obs: False

agent_output_type: "pi_logits"
learner: "actor_critic_learner"
standardise_returns: False
critic_type: "ac_critic"

name: "ia2c"

t_max: 40_050_000
