# --- INDA2C specific parameters ---
hidden_dim: 128 # MPE
lr: 0.0005 # MPE
standardise_rewards: True # MPE
use_rnn: False # MPE
entropy_coef: 0.01  # MPE
target_update_interval_or_tau: 0.01 # MPE
q_nstep: 10 # MPE: 1 corresponds to normal r + gammaV
# update the target network every {} training steps

action_selector: "soft_policies"
mask_before_softmax: True

runner: "parallel"
buffer_size: 10
batch_size_run: 10
batch_size: 10

env_args:
  state_last_action: False # critic adds last action internally
  joint_rewards: False
  time_limit: 25


obs_agent_id: False
obs_last_action: False
obs_individual_obs: False

mac: "dac"
agent: "rnn_ns"
agent_output_type: "pi_logits"
learner: "actor_critic_decentralized_learner"
standardise_returns: False
critic_type: "ac_critic_dec"

name: "inda2c"
t_max: 20_050_000

