# --- IQL specific parameters ---
hidden_dim: 128 # LBF
lr: 0.0003 # LBF
# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 200_000  # LBF
evaluation_epsilon: 0.05  # LBF
runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval_or_tau: 200  # LBF

obs_agent_id: True
obs_last_action: False
obs_individual_obs: False

# use the Q_Learner to train
agent_output_type: "q"
learner: "q_learner"
standardise_returns: False
standardise_rewards: True # LBF
double_q: True
use_rnn: True   # LBF
mixer: # Mixer becomes None

name: "iql"
t_max: 2_050_000
