# --- IQL specific parameters ---
hidden_dim: 128   # MPE
lr: 0.0005    # MPE
standardise_rewards: True
use_rnn: False
evaluation_epsilon: 0.00     # MPE
epsilon_anneal_time: 200_000
# update the target network every {} episodes
target_update_interval_or_tau: 0.01 # MPE

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
runner: "episode"

buffer_size: 5000


env_args:
  pretrained_wrapper: "PretrainedTag" # MPE
  time_limit: 25 # MPE: Max seq_length

obs_agent_id: True
obs_last_action: False
obs_individual_obs: False

# use the Q_Learner to train
agent_output_type: "q"
learner: "q_learner"
standardise_returns: False
double_q: True
mixer: # Mixer becomes None

name: "iql"
t_max: 2_010_000 # MPE
