# --- IQL NS specific parameters ---
hidden_dim: 64 # RWARE: Size of hidden state for default rnn agent
lr: 0.0005 # RWARE:  Learning rate for agents
# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50_000 # RWARE
evaluation_epsilon: 0.05 # RWARE

runner: "episode"

buffer_size: 5_000

# update the target network every {} episodes
target_update_interval_or_tau: 0.01 # RWARE


env_args:
  joint_rewards: True
  shared_rewards: False
  time_limit: 500

obs_agent_id: False
obs_last_action: False
obs_individual_obs: False

# use the Q_Learner to train
mac: "non_shared_mac"
agent: "rnn_ns"
agent_output_type: "q"
learner: "q_learner"
standardise_returns: False
standardise_rewards: True
double_q: True
use_rnn: False # RWARE
mixer: # Mixer becomes None

name: "iql_ns"
t_max: 10_050_000 # LBF
