# --- IQL NS specific parameters ---
lr: 0.0003 # LBF: Learning rate for agents
hidden_dim: 64 # LBF: Size of hidden state for default rnn agent
# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50_000
evaluation_epsilon: 0.05

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval_or_tau: 200 # LBF


env_args:
  joint_rewards: True
  shared_rewards: False
  time_limit: 50 # LBF: Max seq_length

obs_agent_id: False
obs_last_action: False
obs_individual_obs: False

# use the Q_Learner to train
mac: "non_shared_mac"
agent: "rnn_ns"
agent_output_type: "q"
learner: "q_learner"
standardise_returns: False
standardise_rewards: True
double_q: True
use_rnn: True # LBF
mixer: # Mixer becomes None

name: "iql_ns"
t_max: 5_050_000
