# --- Central-V specific parameters ---
hidden_dim: 128 # LBF
lr: 0.0005  # LBF
standardise_rewards: True     # LBF
use_rnn: True      # LBF
entropy_coef: 0.01  # LBF
# update the target network every {} training steps
target_update_interval_or_tau: 0.01  # LBF
q_nstep: 10 # 1 corresponds to normal r + gammaV

action_selector: "soft_policies"
mask_before_softmax: True

runner: "parallel"
buffer_size: 10
batch_size_run: 10
batch_size: 10

env_args:
  state_last_action: False # critic adds last action internally

obs_agent_id: True
obs_last_action: False
obs_individual_obs: False

agent_output_type: "pi_logits"
learner: "actor_critic_learner"
standardise_returns: False
critic_type: "cv_critic"

name: "maa2c"
t_max: 40_050_000
