# --- NTWA2C specific parameters ---
hidden_dim: 64 # LBF
lr: 0.0005 # LBF
use_rnn: True
standardise_rewards: True
entropy_coef: 0.01
# update the target network every {} training steps
target_update_interval_or_tau: 0.01 # LBF
q_nstep: 5 # 1 corresponds to normal r + gammaV

action_selector: "soft_policies"
mask_before_softmax: True

runner: "parallel"
buffer_size: 10
batch_size_run: 10
batch_size: 10

env_args:
  state_last_action: False # critic adds last action internally
  joint_rewards: True
  
obs_agent_id: False
obs_last_action: False
obs_individual_obs: False
mac: "dac"
agent: "rnn_ns"
agent_output_type: "pi_logits"
learner: "actor_critic_networked_learner"
standardise_returns: False
critic_type: "ac_critic_networked" # All weights begin at the same place.
networked_edges: 1  # maps n_agents: n_edges
networked_rounds: 10  # At each consensus round try this many consensus matrices.
networked_interval: 5 # Try consensus at every networked_interval number of training steps.
networked_joint_observations: False # Uses joint observations for training and consensus.


name: "ntwa2c"
t_max: 20_050_000
