# --- NTWQL specific parameters ---
#
# Hyperparameter search: lbforaging
#
hidden_dim: 64 # LBF
lr: 0.0003 # LBF
standardise_rewards: True # LBF
use_rnn: True # LBF
evaluation_epsilon: 0.05 # LBF
epsilon_anneal_time: 50_000 # LBF
# update the target network every {} episodes
target_update_interval_or_tau: 200 # LBF

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05

runner: "episode"
buffer_size: 5000
env_args:
  time_limit: 50 # LBF: Max seq_length
  joint_rewards: True
obs_agent_id: False
obs_last_action: False
obs_individual_obs: False

# use the Q_Learner to train
mac: "dac"
agent: "rnn_ns"
agent_output_type: "q"
learner: "q_networked_learner"
standardise_returns: False
double_q: True
mixer: # Mixer becomes None

# Networked agents
networked_edges: 2  # maps n_agents: n_edges
networked_rounds: 1  # At each consensus round try this many consensus matrices.
networked_joint_observations: False # Uses joint observations for training and consensus.
networked_interval: 10 # Try consensus at every networked_interval number of training steps.

name: "ntwql"
t_max: 2_050_000
