# --- PIC specific parameters ---
hidden_dim: 64  # LBF
lr: 0.0003  # LBF
standardise_rewards: True  # LBF
use_rnn: False #LBF
reg: 0.001 # LBF
# update the target network every {} episodes
target_update_interval_or_tau: 200 # LBF

runner: "episode"
buffer_size: 50000
batch_size: 32

env_args:
  state_last_action: False # critic adds last action internally
  joint_rewards: True

obs_agent_id: True
obs_last_action: False
obs_individual_obs: False


# use the madddpg_learner to train
mac: "maddpg_mac"

standardise_returns: False
learner: "pic_learner"
agent_output_type: "pi_logits"
critic_type: "ac_pic"
pool_type: "max"
name: "pic"
t_max: 2_005_000
