# --- VDN_NS specific parameters ---
#
# Hyperparameter search: lbforaging
#
hidden_dim: 64  # LBF
lr: 0.0001 # LBF
standardise_rewards: True # LBF
use_rnn: True # LBF
evaluation_epsilon: 0.05  # LBF
epsilon_anneal_time: 50_000 # LBF
# update the target network every {} episodes
target_update_interval_or_tau: 200  # LBF
  #
# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05

runner: "episode"
buffer_size: 5000
env_args:
  time_limit: 50
  joint_reward: True
obs_agent_id: False
obs_last_action: False
obs_individual_obs: False

# use the Q_Learner to train
mac: "non_shared_mac"
agent: "rnn_ns"
standardise_returns: False
agent_output_type: "q"
learner: "q_learner"
double_q: True
mixer: "vdn"

name: "vdn_ns"
t_max: 2_010_000
