# --- VDN_NS specific parameters ---
lr: 0.0005 # MPE: Learning rate for agents
# use epsilon greedy action selector
hidden_dim: 128 # MPE: Size of hidden state for default rnn agent
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50_000
evaluation_epsilon: 0.00 # MPE: Reproducibility 

runner: "episode"

buffer_size: 5_000

# update the target network every {} episodes
target_update_interval_or_tau: 200 # MPE

env_args:
  pretrained_wrapper: "PretrainedTag" # MPE
  time_limit: 25 # MPE: Max seq_length

obs_agent_id: False
obs_last_action: False
obs_individual_obs: False


# use the Q_Learner to train
mac: "non_shared_mac"
agent: "rnn_ns"
standardise_returns: False
standardise_rewards: True
use_rnn: False
agent_output_type: "q"
learner: "q_learner"
double_q: True
mixer: "vdn"

name: "vdn_ns"
t_max: 2_010_000 # MPE
