env: "gymma"

env_args:
  key: null
  time_limit: 50
  pretrained_wrapper: null
  joint_rewards: False

test_greedy: True
test_nepisode: 100
test_interval: 500000
log_interval: 500000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 20500000

