env: "gymma"

env_args:
  key: null
  time_limit: 25
  pretrained_wrapper: null
  joint_rewards: False

test_greedy: True
test_nepisode: 100
test_interval: 250_000
log_interval: 250_000
runner_log_interval: 10_000
learner_log_interval: 10_000
t_max: 10_500_000

