env: "gymma"

env_args:
  key: null
  time_limit: 25
  pretrained_wrapper: null

test_greedy: True
test_nepisode: 100
test_interval: 125_000
log_interval: 62_500
learner_log_interval: 10_000
runner_log_interval: 10_000
t_max: 5_010_000 # MPE

