env: "gymma"

env_args:
  key: null
  time_limit: 50
  pretrained_wrapper: null

test_greedy: True
test_nepisode: 100
test_interval: 50_000
log_interval: 50_000
runner_log_interval: 10_000
learner_log_interval: 10_000
t_max: 2_050_000

