env: "gymma"

env_args:
  key: null
  time_limit: 500
  pretrained_wrapper: null
  joint_rewards: False

test_greedy: True
test_nepisode: 100
test_interval: 500_000
log_interval: 500_000
runner_log_interval: 10_000
learner_log_interval: 10_000
# t_max: 20500000
t_max: 30_050_000

