exclude: null
grid-search:

  "--config":
    - "ntwa2c"

  lr:
    - 0.0001
  #   - 0.0003
  #   - 0.0005

  standardise_rewards:
    - True

  use_rnn:
    - True
    - False

  # target_update_interval_or_tau:
  #   - 200
  #   - 0.01

  hidden_dim:
    - 64
    - 128

  entropy_coef: 
    - 0.01
    - 0.001

  networked_rounds:
    - 1
    - 5

  q_nstep:
    - 5
    - 10

  # evaluation_epsilon:
  #   - 0.0
  #   - 0.05

  t_max:
    - 20_050_000
    
  test_nepisode:
    - 100

  test_interval:
    - 500000

  log_interval:
    - 10000

  save_model_interval:
    - 50000

  save_model:
    - False
    
grid-search-groups:
  env0:
    - "--env-config": "gymma"
    - env_args.key: lbforaging:Foraging-15x15-3p-4f-v1
    - env_args.time_limit: 51
